name: Ecosystem CI

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

on:
  workflow_dispatch:
    inputs:
      version:
        description: "swc version to use"
        required: true
        type: string
        default: "nightly"
      suite:
        description: "test suites to run. Select _ to run all tests"
        required: true
        type: string

jobs:
  execute-selected-suite:
    name: Test ${{ inputs.suite }} with ${{ inputs.version }}
    timeout-minutes: 30
    concurrency:
      group: swc-ci-project=${{ inputs.suite }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
        id: setup-node
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
        id: setup-deno
        continue-on-error: true
      - run: corepack enable
      - run: pnpm --version
      - run: pnpm i --frozen-lockfile
      - run: >-
          pnpm tsx ecosystem-ci.ts run-suites ${{ inputs.suite }}
          --release ${{ inputs.version }}
        id: ecosystem-ci-run

      - if: failure()
        name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            Test for `${{ inputs.suite }}` with `${{ inputs.version }}` failed.
            See https://github.com/swc-project/swc-ecosystem-ci/actions/runs/${{ github.run_id }} for details.
